module.exports = {
  gameframework: [
    {
      type: "category",
      label: "Classes",
      link: {
        type: "doc",
        id: "gameframework/classes",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "gameframework/classess",
        },
      ],
    },
    {
      type: "category",
      label: "Typedefs",
      link: {
        type: "doc",
        id: "gameframework/typedefs",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "gameframework/typedefss",
        },
      ],
    },
    {
      type: "category",
      label: "Enums",
      link: {
        type: "doc",
        id: "gameframework/enums",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "gameframework/enumss",
        },
      ],
    },
    {
      type: "category",
      label: "Functions",
      link: {
        type: "doc",
        id: "gameframework/functions",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "gameframework/functionss",
        },
      ],
    },
    {
      type: "category",
      label: "Variables",
      link: {
        type: "doc",
        id: "gameframework/variables",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "gameframework/variabless",
        },
      ],
    },
  ],
};

// Typedefs
