module.exports = {
  gameframework: [
    {
      type: "category",
      label: "Classes",
      link: {
        type: "doc",
        id: "gameframework/classes",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "gameframework/classes",
        },
      ],
    },
    {
      type: "doc",
      label: "Typedefs",
      id: "gameframework/typedefs",
    },
    {
      type: "doc",
      label: "Enums",
      id: "gameframework/enums",
    },
    {
      type: "doc",
      label: "Functions",
      id: "gameframework/functions",
    },
    {
      type: "doc",
      label: "Variables",
      id: "gameframework/variables",
    },
  ],
};

// Typedefs
